#name: pam_wewe_sonarqube

services:
  sonarqube:
    image: docker.io/sonarqube:developer
    container_name: sonarqube
    ports:
      - "9000:9000"
#     volumes:
#       - sonarqube_conf:/opt/sonarqube/conf
#       - sonarqube_data:/opt/sonarqube/data
#       - sonarqube_extensions:/opt/sonarqube/extensions
#       - sonarqube_logs:/opt/sonarqube/logs

# volumes:
#   sonarqube_conf:
#   sonarqube_data:
#   sonarqube_extensions:
#   sonarqube_logs:
